### ISSUE TITLE
Failure installing on Apple Silicon

### ISSUE THREAD

**Issue by nodesocket** [thevahidal/soul#46]
OS: macOS Ventura 13.0
Architecture: arm64
Node: v14.20.1
NPM: 6.14.17

```bash
MacBook-Pro ➜  npm install -g soul-cli
/Users/justin/.nvm/versions/node/v14.20.1/bin/soul -> /Users/justin/.nvm/versions/node/v14.20.1/lib/node_modules/soul-cli/soul/index.js

> better-sqlite3@7.6.2 install /Users/justin/.nvm/versions/node/v14.20.1/lib/node_modules/soul-cli/node_modules/better-sqlite3
> prebuild-install || npm run build-release

prebuild-install warn install No prebuilt binaries found (target=14.20.1 runtime=node arch=arm64 libc= platform=darwin)

> better-sqlite3@7.6.2 build-release /Users/justin/.nvm/versions/node/v14.20.1/lib/node_modules/soul-cli/node_modules/better-sqlite3
> node-gyp rebuild --release

  TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
env: python: No such file or directory
make: *** [Release/sqlite3.a] Error 127
rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/justin/.nvm/versions/node/v14.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 22.1.0
gyp ERR! command "/Users/justin/.nvm/versions/node/v14.20.1/bin/node" "/Users/justin/.nvm/versions/node/v14.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/justin/.nvm/versions/node/v14.20.1/lib/node_modules/soul-cli/node_modules/better-sqlite3
gyp ERR! node -v v14.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.6.2 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.6.2 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/justin/.npm/_logs/2022-10-29T23_55_45_410Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.6.2 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.6.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/justin/.npm/_logs/2022-10-29T23_55_45_567Z-debug.log
```

**Comment by thevahidal** [comment]
Hi @nodesocket,
Better-Sqlite3 is one of the main dependencies of Soul and it seems that it is the source of the issue.
I looked around a little bit and found these, please try them out and let me know if it works:
- https://github.com/nodejs/node-gyp#on-macos
- https://github.com/libxmljs/libxmljs/issues/469#issuecomment-309605567

**Comment by srdjanfadv** [comment]
I don't want to open another issue, since I think my issue is related/same and happening on a macos running on intel ...
I have installed better-sqlite3 separately, without issues - but installing soul-cli tries to build it again and fails...

OS: macOS Ventura 13.0
Architecture: x64
Node: v19.2.0
NPM: 8.19.3

❯   npm install -g soul-cli
npm ERR! code 1
npm ERR! path /Users/Strbansr/.nvm/versions/node/v19.2.0/lib/node_modules/soul-cli/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c -- prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.6.2 build-release
npm ERR! > node-gyp rebuild --release
npm ERR! 
npm ERR!   TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
npm ERR!   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
npm ERR!   LIBTOOL-STATIC Release/sqlite3.a
npm ERR!   CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
npm ERR! rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! prebuild-install warn install No prebuilt binaries found (target=19.2.0 runtime=node arch=x64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@19.2.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.8 found at "/usr/local/opt/python@3.10/bin/python3.10"
npm ERR! gyp info spawn /usr/local/opt/python@3.10/bin/python3.10
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/Strbansr/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/Strbansr/.nvm/versions/node/v19.2.0/lib/node_modules/soul-cli/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/Strbansr/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/Strbansr/Library/Caches/node-gyp/19.2.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/Strbansr/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/Strbansr/Library/Caches/node-gyp/19.2.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/Strbansr/.nvm/versions/node/v19.2.0/lib/node_modules/soul-cli/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/better_sqlite3.cpp:4:
npm ERR! In file included from ./src/better_sqlite3.lzz:11:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/node.h:73:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8.h:24:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-array-buffer.h:12:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-local-handle.h:12:
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:476:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! SHARED_EXTERNAL_POINTER_TAGS(CHECK_SHARED_EXTERNAL_POINTER_TAGS)
npm ERR!                              ^
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:476:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:476:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:476:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:476:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! PER_ISOLATE_EXTERNAL_POINTER_TAGS(CHECK_NON_SHARED_EXTERNAL_POINTER_TAGS)
npm ERR!                                   ^
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:477:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:658:61: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR!     static_assert(kJSObjectType + 1 == kFirstJSApiObjectType);
npm ERR!                                                             ^
npm ERR!                                                             , ""
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:659:55: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR!     static_assert(kJSObjectType < kLastJSApiObjectType);
npm ERR!                                                       ^
npm ERR!                                                       , ""
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-internal.h:660:63: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
npm ERR!     static_assert(kFirstJSApiObjectType < kLastJSApiObjectType);
npm ERR!                                                               ^
npm ERR!                                                               , ""
npm ERR! In file included from ../src/better_sqlite3.cpp:4:
npm ERR! In file included from ./src/better_sqlite3.lzz:11:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/node.h:73:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8.h:24:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-array-buffer.h:13:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-object.h:9:
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-maybe.h:106:45: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
npm ERR!   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
npm ERR!                                        ~~~~~^~~~~~~~~~~~~~~~~~~~~
npm ERR!                                             is_lvalue_reference
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:910:29: note: 'is_lvalue_reference' declared here
npm ERR! struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
npm ERR!                             ^
npm ERR! In file included from ../src/better_sqlite3.cpp:4:
npm ERR! In file included from ./src/better_sqlite3.lzz:11:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/node.h:73:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8.h:24:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-array-buffer.h:13:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-object.h:9:
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-maybe.h:106:69: error: expected '(' for function-style cast or type construction
npm ERR!   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
npm ERR!                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-maybe.h:123:43: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
npm ERR! template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
npm ERR!                                      ~~~~~^~~~~~~~~~~~~~~~~~~~~
npm ERR!                                           is_lvalue_reference
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:910:29: note: 'is_lvalue_reference' declared here
npm ERR! struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
npm ERR!                             ^
npm ERR! In file included from ../src/better_sqlite3.cpp:4:
npm ERR! In file included from ./src/better_sqlite3.lzz:11:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/node.h:73:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8.h:24:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-array-buffer.h:13:
npm ERR! In file included from /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-object.h:9:
npm ERR! /Users/Strbansr/Library/Caches/node-gyp/19.2.0/include/node/v8-maybe.h:123:67: error: expected '(' for function-style cast or type construction
npm ERR! template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
npm ERR!                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
npm ERR! ./src/util/macros.lzz:157:21: error: no member named 'AccessorSignature' in namespace 'v8'
npm ERR!                 v8::AccessorSignature::New(isolate, recv)
npm ERR!                 ~~~~^
npm ERR! ./src/objects/database.lzz:180:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
npm ERR!                 int status = sqlite3_db_config(db_handle, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, 1, NULL);
npm ERR!                     ^
npm ERR! ./src/util/binder.lzz:37:51: error: no member named 'CreationContext' in 'v8::Object'
npm ERR!                 v8::Local<v8::Context> ctx = obj->CreationContext();
npm ERR!                                              ~~~~~^
npm ERR! 20 warnings and 6 errors generated.
npm ERR! make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/Strbansr/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/Users/Strbansr/.nvm/versions/node/v19.2.0/bin/node" "/Users/Strbansr/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/Strbansr/.nvm/versions/node/v19.2.0/lib/node_modules/soul-cli/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v19.2.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

**Comment by srdjanfadv** [comment]
I have managed to complete the installation. So, in case  this helps someone else:

- downgraded Node from v19.2.0 to v18.12.1 and npm installation completed
- the install skipped building better-sqlite3, so I did it manually (ran npm run install in the node_modules/better-sqlite3)

Not ideal, but it works.
