### ISSUE TITLE
`better-sqlite3` installation keeps failing when i run `npm install` in the core folder (for MacOs)

### ISSUE THREAD

**Issue by AbegaM** [thevahidal/soul#74]
When i run `npm install` in the core folder, `better-sqlite3` installation keeps failing due to `node-gyp`

**To Reproduce**
1. Go to the `/soul/core` folder 
2. Run `npm install` 

![Screen Shot 2022-11-29 at 12 51 34 PM](https://user-images.githubusercontent.com/70259638/204496785-609a6f33-d601-408f-83cf-215c1bee104d.png)

**Expected behavior**
I was expecting all of the packages to be installed in the `node_modules` folder so i can run the core API

**OS**
 - OS: Macos Montery 12.6
 - Browser: Chrome

**Comment by thevahidal** [comment]
Hi @AbegaM,
This issue is happening on Apple Silicon and is related to `better-sqlite3` as you mentioned. Check out this other issue #46.
You'll find some useful links there. If it didn't work try looking in `better-sqlite3` issues. Unfortunately, I don't own a mac device to test it myself.

Let me know if you still have questions.

**Comment by AbegaM** [comment]
@thevahidal thank you i have fixed the issue

**Comment by thoughtsunificator** [comment]
Thanks for helping the community and posting how you solved the issue!
